apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-mwttkaqa
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-mwttkaqa:68ae75c67d0713425a67e0341748fcd02836c17f@sha256:3660d9e9daf08c9b65d8ea7e4b28501208592392bacf1cc8ed17758208730ff7
          name: container-image
